"""empty message

Revision ID: 68915b50577d
Revises: 
Create Date: 2025-07-09 13:21:55.290811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68915b50577d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gene_symbol'), ['symbol'], unique=False)

    with op.batch_alter_table('rnaediting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rnaediting_chromosome'), ['chromosome'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rnaediting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rnaediting_chromosome'))

    with op.batch_alter_table('gene', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gene_symbol'))

    # ### end Alembic commands ###
